name: ci/cd

on:
  push:
    branches: [main, release/*]
  pull_request:
    branches: [main, release/*]

jobs:
  build:
    name: Build on OpenJDK ${{ matrix.jdk_version }} / ${{ matrix.os }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # JDK LTS: 8, 11, 17
        jdk_version: [8, 11, 17]
        os: [ubuntu-latest]

    container:
      image: clojure:openjdk-${{ matrix.jdk_version }}-lein

    steps:
      - uses: actions/checkout@v2
      - name: Prep
        run: |
          apt update
          apt install -y make
      - name: Info
        run: make debug
      - name: Tests
        run: make test
      - name: Package
        run: make package
