name: ci/cd

on:
  push:
    branches: [main, release/*]
  pull_request:
    branches: [main, release/*]

jobs:
  build:
    name: Build on OpenJDK ${{ matrix.jdk_version }} / ${{ matrix.os }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # JDK LTS: 8, 11, 17
        jdk_version: [8, 11, 17]
        os: [ubuntu-latest]

    container:
      image: clojure:openjdk-${{ matrix.jdk_version }}-lein

    steps:
      - uses: actions/checkout@v2
      - name: Dependencies
        run: lein deps
      - name: Version
        run: lein version
      - name: Build
        run: lein compile
      - name: Test JSON with 'cheshire'
        run: lein with-profiles +cheshire test :json
      - name: Test JSON with 'jsonista'
        run: lein with-profiles +jsonista test :json
      - name: Test JSON with 'data.json'
        run: lein with-profiles +data.json test :json
      - name: Test everything else
        run: lein with-profiles +cheshire test
      - name: Package
        run: lein uberjar
